site_name: NEXUS
theme:
  name: material
nav:
  - Home: index.md
  - Overview & Installation: Overview & Installation.md
  - Basic Syntax: Basic Syntax.md
  - Compound Datatypes: Compound Datatypes.md
  - Conditionals & Loops: Conditionals & Loops.md
  - Functions & Scoping: Functions & Scoping.md
  - Bytecode: Bytecode.md
